name: navi-dock

services:
  navi-dock:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${APP_VERSION:-}
    image: navi-dock:latest
    container_name: navi-dock
    ports:
      - "${SERVER_PORT:-7530}:7530"
    env_file:
      - .env
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      APP_VERSION: ${APP_VERSION:-}
      LAN_PROBE_DOMAIN: ${LAN_PROBE_DOMAIN:-}
    volumes:
      - ./data:/data
    restart: unless-stopped
